### ISSUE TITLE
Missing information read me 

### ISSUE THREAD

**Issue by cece46** [pkuehnel/SmartTeslaAmpSetter#98]
hello, what is the date and time for here (in red)?  thank you
![30952E28-2279-45A8-B1FC-2ACF864CBC7D](https://user-images.githubusercontent.com/32593390/165031191-d97fb5ae-7687-4421-b3e8-e873d63e3a7c.jpeg)

**Comment by pkuehnel** [comment]
If date is in the future and solar power is not enough to reach minimum SOC the car starts to charge with full speed, to reach minimum SOC in time. So if you have a trip starting at 06:00 and you need at least 70% SOC the car starts charging at full speed even though there is no Solar power, to reach 70% in time.

Will clarify that in readme
